id: P000459
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:02.957722
source_metadata:
  id: bdr:W27876
  title: རྡོ་རྗེ་ཉི་མའི་གནས་ཡིག་གསང་བའི་དཀར་ཆག
  author: ''
  volumes:
    dcfb045bf16149a296c330697e056c53:
      image_group_id: I4495
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
