id: P000459
initial_creation_type: ocr
source_metadata:
  id: bdr:W27876
  title: རྡོ་རྗེ་ཉི་མའི་གནས་ཡིག་གསང་བའི་དཀར་ཆག
  author: ''
  volumes:
    dcfb045bf16149a296c330697e056c53:
      image_group_id: I4495
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
ebook_metadata:
  title: རྡོ་རྗེ་ཉི་མའི་གནས་ཡིག་གསང་བའི་དཀར་ཆག
  author: ''
  sku: P000459
  cover: cover.jpg
  layers:
  - pagination
